name: Download Kaggle Dataset

on:
  push:
    branches:
      - feature-retrive-dataset
permissions:
  contents: write
jobs:
  download_dataset:
    runs-on: ubuntu-latest

    steps:

    - name: Check out repository code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}
        ref: feature-retrive-dataset

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Download dataset
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: |
        if [ -d "dataset" ]; then
          echo "Deleting existing dataset directory"
          rm -rf dataset
        fi
        mkdir dataset
        kaggle datasets download -d mmmarchetti/transfusion-dataset -p dataset
        unzip dataset/transfusion-dataset.zip -d dataset

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        if git diff --staged --quiet; then
          echo "No changes in the dataset, skipping commit and push."
        else
          git add dataset/*
          git commit -m "Add dataset"
          git push
        fi
 
